import { registerSW } from "virtual:pwa-register"

// Registers the service worker generated by vite-plugin-pwa.
// No UI prompts for updates; the SW auto-updates in the background.
void registerSW({
  immediate: true,
})
