/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ListRouteImport } from './routes/List'
import { Route as BudgetRouteImport } from './routes/Budget'
import { Route as IndexRouteImport } from './routes/index'

const ListRoute = ListRouteImport.update({
  id: '/List',
  path: '/List',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/Budget',
  path: '/Budget',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Budget': typeof BudgetRoute
  '/List': typeof ListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Budget': typeof BudgetRoute
  '/List': typeof ListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Budget': typeof BudgetRoute
  '/List': typeof ListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Budget' | '/List'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Budget' | '/List'
  id: '__root__' | '/' | '/Budget' | '/List'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetRoute: typeof BudgetRoute
  ListRoute: typeof ListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/List': {
      id: '/List'
      path: '/List'
      fullPath: '/List'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Budget': {
      id: '/Budget'
      path: '/Budget'
      fullPath: '/Budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetRoute: BudgetRoute,
  ListRoute: ListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
